### ISSUE TITLE
Add natural stop() effect

### ISSUE THREAD

**Issue by laresbernardo** [hypebright/fireworks#1]
Thanks for building this really nice add-on. I'm adding it so that it gets triggered once the user marks as finished a whole process of a shiny app I'm working on. Nice (hidden) touch! 

Sharing the code as an additional use-case where the fireworks are triggered for 5 seconds and then stop. In case you'd like me to add it to the README, let me know.

# In UI
`checkboxInput("final_model", "Report as final model", FALSE)`

# In server
```
  fw <- fireworks::Fireworks$new()
  observeEvent(input$final_model, {
    fw$stop()
    if (isTRUE(input$final_model)) {
      fw$start()
      Sys.sleep(5)
      fw$stop()
    }
  })
```

Finally, regarding the "special effects", is there a way to set `stop()` to stop "launching fireworks" instead of simply getting rid of all at the same time to have a more natural stopping effect?

**Comment by hypebright** [comment]
Thanks for raising this @laresbernardo .

I can leverage [updateOptions](https://github.com/crashmax-dev/fireworks-js/?tab=readme-ov-file#updateoptionsoptions) to add an "fade out" effect. It can then be provided as an argument to `stop()`, like so:

```
fw <- Fireworks$new()
fw$start()
Sys.sleep(5)
fw$stop(fadeOut = TRUE)
```
